spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:12306/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: fuckinghackers
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

